# Generated by Django 5.1.2 on 2024-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosme',
            name='Ingredient_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosme',
            name='large_categories',
            field=models.CharField(choices=[('makeup', 'メイクアップ'), ('base', 'ベースメイク'), ('skincare', 'スキンケア')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
