# Generated by Django 5.1.2 on 2024-10-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Cosme',
            new_name='cosme',
        ),
        migrations.AddField(
            model_name='cosme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
