# Generated by Django 5.1.2 on 2024-10-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0005_cosme_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_categories', models.CharField(max_length=100)),
                ('medium_categories', models.CharField(max_length=100)),
                ('sub_categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cosme',
            name='large_categories',
        ),
        migrations.AddField(
            model_name='cosme',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5')]),
        ),
        migrations.AddField(
            model_name='cosme',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmereview.brand'),
        ),
        migrations.AddField(
            model_name='cosme',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmereview.category'),
        ),
    ]
