# Generated by Django 5.1.2 on 2024-10-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0006_brand_category_remove_cosme_large_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(default='', upload_to='brand/brand_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(default='', upload_to='brand/brand_icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='official_website_stores_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='official_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosme',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmereview.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cosme',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmereview.category'),
            preserve_default=False,
        ),
    ]
