# Generated by Django 5.1.2 on 2024-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0007_brand_brand_description_brand_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cosme',
            name='tag',
        ),
        migrations.AlterField(
            model_name='brand',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/brand_covers/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='brand/brand_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cosme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cosme/'),
        ),
        migrations.AddField(
            model_name='cosme',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='cosmereview.tag'),
        ),
    ]
