# Generated by Django 5.1.2 on 2024-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0008_tag_remove_cosme_tag_alter_brand_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='送信先メールアドレス')),
                ('sender', models.EmailField(max_length=254, verbose_name='送信元メールアドレス')),
                ('subject', models.CharField(max_length=255, verbose_name='メールタイトル')),
                ('body', models.TextField(verbose_name='メール本文')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
        ),
    ]
