# Generated by Django 5.1.2 on 2024-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmereview', '0009_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
